# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://nicolekeeney.com
baseurl: /nicolejkeeney.github.io/
title: Nicole Keeney
author: Nicole Keeney
description: Personal website
avatar: profile.png
resume: https://drive.google.com/file/d/1lBG5LixBq5RqiFw1AwZK_5xVt7tJvUxU/view?usp=sharing
email: nicolejkeeney@gmail.com
github: nicolejkeeney # username
#twitter: username
linkedin: nicole-keeney
#stackoverflow: username   #e.g: users/2735833/proton1h1
#medium: username #e.g: NobelPeaceOslo
#Comment out if you don't want disqus
#disqus: username
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
